### ISSUE TITLE
Removed from npm?

### ISSUE THREAD

**Issue by karl-sjogren** [smrtlabs/smrt-gulp-r#7]
Starting from sometime earlier today I can't install this package from NPM anymore.

Browsing to it's page on npmjs.com also returns a 404: https://www.npmjs.com/package/gulp-r

Was this intentional and if so, for what reason was it removed? If not it would be great if it could be restored as soon as possible!

**Comment by karl-sjogren** [comment]
Seems this has been resolved, thanks!

**Comment by mcharytoniuk** [comment]
No problem, sorry for the issue. We will publish deprecation notes shortly because gulp approach does not give much advantages here.

Please try using pure require.js wrapper instead of this package:

``` JavaScript
gulp.task("requirejs", function (done) {
    requirejs.optimize({
        "baseUrl": path.join(__dirname, "s"),
        "generateSourceMaps": true,
        "include": [
            "requirejs",
            ...
        ],
        "optimize": "uglify2",
        "out": path.join(__dirname, "s", "all.js"),
        "paths": {
            "jquery": "bower_components/jquery/dist/jquery",
            ...
        },
        // for source maps
        "preserveLicenseComments": false,
        "wrapShim": false
    }, function () {
        done();
    }, done);
});
```

You can also check http://github.com/goreutils/gore-gulp for automated project building.
